creategenesis: true
witnessinfo:
- IOSTfQFocqDn7VrKV7vvPqhAQGyeFU9XMYo5SNn5yQbdbzC75wM7C
- "2100000000000000000"
votecontractpath: contract/
adminid: IOSTbbKmaZi1QRMfd7K8bK22KQSFuKadLhSNBw6tmyCHCRSvTr9QN
initialtimestamp: "2006-01-02T15:04:05Z"
