acc:
  id: producer00001
  seckey: 1rANSfcRzr4HkhbUFZ7L1Zp69JZZHiDDq5v7dNSbbEqeU4jxy3fszV4HGiaLQEyqVpS1dKT9g7zCVRxBVzuiUzB
  algorithm: ed25519
genesis: config/genesis.yml
vm:
  jspath: vm/v8vm/v8/libjs/
  loglevel: ""
db:
  ldbpath: storage/
p2p:
  listenaddr: 0.0.0.0:30000
  seednodes:
  chainid: 1024
  version: 1
  datapath: p2p/
  inboundConn: 15
  outboundConn: 15
  blackPID:
  blackIP:
  adminPort: 30005
rpc:
    gatewayaddr: 0.0.0.0:30001
    grpcaddr: 0.0.0.0:30002
log:
  filelog:
    path: logs/
    level: info
    enable: true
  consolelog:
    level: info
    enable: true
  asyncwrite: true
metrics:
  pushAddr:
  username:
  password:
  enable: false
  id: iost-testnet:visitor00
debug:
  listenaddr: 0.0.0.0:30003
version:
  netname: "debugnet"
  protocolversion: "1.0"
