acc:
  id: "IOSTjBxx7sUJvmxrMiyjEQnz9h5bfNrXwLinkoL9YvWjnrGdbKnBP"
  seckey: "5ifJUpGWJ69S2eKsKYLDcajVxrc5yZk2CD7tJ29yK6FyjAtmeboK3G4Ag5p22uZTijBP3ftEDV4ymXZF1jGqu9j4"
  algorithm: "ed25519"
genesis:
  createGenesis: false
  genesisHash: "BSUxNfQcHmTviuNEiN18GW4fhXXYbV9sRCFzJFJLYNhb"
  witnessInfo:
    - "IOSTjBxx7sUJvmxrMiyjEQnz9h5bfNrXwLinkoL9YvWjnrGdbKnBP"
    - "13400000000"
    - "IOSTgw6cmmWyiW25TMAK44N9coLCMaygx5eTfGVwjCcriEWEEjK2H"
    - "13200000000"
    - "IOSTxHn7wtQMpgvDbiypByZVNHrE6ELdXFbL1Vic8B23EgRNjQGbs"
    - "13100000000"

vm:
  logLevel: "debug"
  jsPath: "vm/v8vm/v8/libjs/"

db:
  ldbpath: "leveldb/"


p2p:
  listenAddr: "0.0.0.0:30303"
  chainID: 1024
  version: 1
  seedNodes:

rpc:
  JSONPort: 30301
  GRPCPort: 30302

log:
  asyncWrite: true
  fileLog:
    path: "logs/"
    level: "info"
    enable: true
  consoleLog:
    level: "debug"
    enable: true

metrics:
  pushAddr: "47.75.42.25:9091"
  enable: true
  id: "1"

debug:
  listenAddr: "0.0.0.0:40303"
